# config.yaml
model:
  arch: xception_ffpp
  num_classes: 2
  ckpt_path: checkpoints/xception_ffpp_c23.pth
  fake_index: 1           # assume index 1 corresponds to "fake"
  input_size: 299
  mean: [0.5, 0.5, 0.5]
  std:  [0.5, 0.5, 0.5]
data:
  fps: 8
  max_frames: 256
  face_detector: mtcnn
  face_margin: 0.25
  min_face: 80
  align_eyes: true
inference:
  batch_size: 64
  half: true
calibration:
  temperature: 1.0
  threshold: 0.5                 # set after val analysis
io:
  save_dir: outputs/probe_2025-10-04
  input_glob: data/videos/**/*.mp4   # used if --dir is given
  manifest: data/manifest.csv        # used if --manifest is given
